name: kabutan-discord

on:
  schedule:
    # 16:00 JST
    - cron: '0 7 * * 1-5'
    # 18:00 JST
    - cron: '0 9 * * 1-5'
    # 土日 18:00 JST
    - cron: '0 9 * * 6,0'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests beautifulsoup4

      - run: python kabutan_discord.py
